name: "open-pull-request-to-main"

on:
  push:
    branches:
      - "staging"

permissions:
  contents: "read"
  pull-requests: "write"

jobs:
  open_pullrequest_to_main:
    name: "open pull request"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Open Pull Request"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |-
          gh pr create --base main --head staging \
            --title "staging to main" --body "staging to main" | true
